import "~/styles/globals.css";

import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"

export const metadata: Metadata = {
  title: "GeM Bids | Unity Blaster",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "https://zu4k1b78pv.ufs.sh/f/5tCflPuyaleWPH3wE1iER8sVv3WJUprA0HqDn9PgBYaZcwi4" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body>{children}</body>
	  <Analytics />
    </html>
  );
}
